--- # zarchitect config file
:url: https://www.example.com
:email: test@example.com
:site_name: My Blog
:site_slogan: slogan
:admin: mar
:origin_year: 2015
:title_sep: " / "
:site_keywords: blog, mar
:thumbl: [640,480]
:thumbs: [320, 240]
:image_limit: 5 # MB
:audio_limit: 10
:video_limit: 20
:sections:
    :profile:
      :layout: _layouts/ellis.html.erb
      :view: _layouts/view/default.html.erb
      :path: profile.md # location of .md files belonging to section
      :index_flag: true
      :index_sort: 1
    :links:
      :layout: _layouts/default.html.erb
      :collection: no
      :path: links.md
      :index_flag: true
      :index_sort: 4
    :blog:
      :layout: _layouts/default.html.erb
      :collection : yes
      :categorize: yes
      :tags: yes
      :path: blog/
      :index_flag: true
      :index_sort: 2
      :sort_type: date # date | alphanum
    :projects:
      :layout: _layouts/default.html.erb
      :paginate: no
      :collection: yes
      :categorize: yes
      :tags: no
      :path: projects/
      :index_flag: true
      :index_sort: 3
      :sort_type: alphanum
    :posts:
      :api: mastodon
      :paginate: yes
      :items: no # only index files are required
      :layout: _layouts/default.html.erb
      :collection: yes
      :categorize: no
      :tags: no
      :path: posts/
      :index_flag: true
      :sort_type: date
:index:
  :sort_type: flag # flag | alphanum
:exclude_assets:
  - .scss
  - .css.map
