--- # zarchitect config file
:url: https://www.example.com
:email: test@example.com
:site_name: My Blog
:site_slogan: slogan
:admin: mar
:origin_year: 2015
:title_sep: " / "
:site_keywords: blog, mar
:thumbl: [640,480]
:thumbs: [320, 240]
:image_limit: 5.0 # MB
:audio_limit: 10.0
:video_limit: 20.0
:sections:
    :profile:
      :layout: _layouts/ellis.html.erb
      :view: _layouts/view/default.html.erb
      :path: profile.md # location of .md files belonging to section
      :index_flag: true
      :index_sort: 1
    :index: # website index page. always last section
      :noitems: yes
      :paginate: 0
      :maxpages: 0 # only create 1 index
      :index_layout: _layouts/hydra.html.erb
      :index_view: _layouts/view/index.html.erb
:index:
  :sort_type: flag # flag | alphanum
:exclude_assets:
  - .scss
  - .css.map
