--- # zarchitect config file
:domain: www.test.com
:email: test@test.com
:sections:
    :first:
      :layout: layouts/default.html.erb
      :collection: no
      :path: content/profile.md # location of .md files belonging to section
      :index_flag: true
      :index_sort: 1
    :links:
      :layout: layouts/default.html.erb
      :collection: no
      :path: content/links.md
      :index_flag: true
      :index_sort: 3
    :second:
      :layout: layouts/default.html.erb
      :collection : yes
      :path: content/blog/
      :index_flag: true
      :index_sort: 2
      :sort_type: date # date | alphanum
:index:
  :sort_type: flag # flag | alphanum
